databases:
  - name: bg-app-production
    databaseName: bg_app_production
    user: bg_app_production_user

services:
  - type: hesab-app
    name: mysite
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bg_app_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false